print("\t-Metehan'in Günlük Görevi".upper())
print("\t-metehan şirkette olan yazilimcilara,şirkete yeni gelen yazilimcilarin isminide Ekle ve son Durumda Şirkette kaç Yazilimci olduğunu Webb sitemize İşle".title())
şirketteki_yazilimcilar = "Asli Murat Berk John Alex".split()
yeni_gelen_yazilimcilar = "Efe Salih".split()
print(f"\t-şirketeki yazilimcilar: {şirketteki_yazilimcilar}\n\t-Şirkete Yeni Katilan Yazilimcilar: {yeni_gelen_yazilimcilar}")
şirketteki_yazilimcilar.extend(yeni_gelen_yazilimcilar)
print(f"\t-Şirketteki Tüm Yazilimcilar: {şirketteki_yazilimcilar}")
print(f"\t-Şirkette Bulunan Yazilimci Sayisi: {len(şirketteki_yazilimcilar)}")

print("\t-ŞİRKETTEN BİR YENİ MESAJ!!!")
print("\t-metehan şirketten alexi uygunsuz davranişlarindan ötürü attik, onu listeden çikar.".title())
print(f"\t-Şirketten Atilan Yazilimci: {şirketteki_yazilimcilar.pop(4)}")
print(f"\t-Şirketteki Güncel Yazilimcilar: {şirketteki_yazilimcilar}")
print(f"\t-Şirketteki Güncel Yazilimci Sayisi: {len(şirketteki_yazilimcilar)}")
